### ISSUE TITLE
MySQL5.6の環境でログの表示が時系列順にならない

### ISSUE THREAD

**Issue by karia** [tyoro/tiarraMetro#81]
MySQL5.6.19の環境でtiarraMetroを立てたところ、ログの表示が時系列順ではなくnick順に並び替えられてしまったのでご報告。

MySQL5.1.73の環境では時系列順で並び替えられていた（期待通り）のでおかしいなと思ったら、下記リファレンスを軽く読んだ感じ、MySQL5.6系では「最終的な出力の並び替えがしたければ明示的にORDER BYを指定しろ」ということのようです。
http://dev.mysql.com/doc/refman/5.6/ja/order-by-optimization.html

なので、対処方としては、

https://github.com/tyoro/tiarraMetro/blob/master/dao.php#L278

```
               JOIN nick ON tmplog.nick_id = nick.id ";
```

ここを

```
               JOIN nick ON tmplog.nick_id = nick.id
               ORDER BY time DESC ";
```

こうしたらとりあえず直りました（けど、これでいいか？という話はありそうなのでとりあえずissue立ててみる）。

**Comment by tyoro** [comment]
当該部分のソースを見てみた感じ、中の副問合せで limit する為に order by でソートしてて、旧版の mysql 上だと、INNER JOIN 時にその順番で結合されていたっぽいけど、MySQL 5.6 系で INNER JOIN 時のソート基準が変わってしまったのかもしれないな。
ORDER BY いれてもらうコード自体は問題解決するし大丈夫な気はするけど、もし明示的に LEFT OUTER JOIN にする事でソート基準がそっちになるなら、その方がいいかもしれない。

外でも ORDER BY すると、外側で filesort する事になって負荷的は増す感じになる。
・元の
![元の](http://gy.tyo.ro/0ab3f.png)
・ORDER BY 追加したの
![元の](http://gy.tyo.ro/ee4b9.png)

ただまぁ、中で LIMIT とった後のたかだか 100 件のソートなんで無視していい問題かもしれんが…

>LEFT JOIN nick ON tmplog.nick_id = nick.id

で検証してみてほしい

**Comment by tyoro** [comment]
ダメだったようなので、おとなしく order by しつつ、他にも必要な場所ないか見ておこう。

**Comment by tyoro** [comment]
再検証の結果、sort 自体は left join で保たれるが、time には重複があり id 順でみると order by time では順序が保証されていない事が分かったので、副問合せの内部の order by を id 順にする事で解決しそう。
